<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Atlas.Edge.ScannerDiscovery\Atlas.Edge.ScannerDiscovery.csproj" />
    <ProjectReference Include="..\Atlas.Edge.ScannerHealth\Atlas.Edge.ScannerHealth.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
